# Generated by Django 2.2 on 2019-05-11 16:50

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.BigIntegerField(primary_key=True, serialize=False, validators=[app.models.test_class_id], verbose_name='班级编号')),
                ('class_name', models.CharField(max_length=100, verbose_name='班级')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('cid', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[app.models.test_cid], verbose_name='课程编号')),
                ('cname', models.CharField(blank=True, max_length=50, verbose_name='课程名称')),
                ('tname', models.CharField(max_length=10, verbose_name='授课教师')),
                ('credit', models.IntegerField(blank=True, verbose_name='学分')),
                ('bestSemester', models.IntegerField(verbose_name='推荐选课学期')),
                ('openTill', models.IntegerField(blank=True, default=9999, verbose_name='开课年份')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('tid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='教师工号')),
                ('tname', models.CharField(max_length=50, verbose_name='教师姓名')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('sid', models.BigIntegerField(primary_key=True, serialize=False, validators=[app.models.test_sid], verbose_name='学号')),
                ('sname', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=50, verbose_name='性别')),
                ('age', models.IntegerField(validators=[app.models.test_age], verbose_name='年龄')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='家庭住址')),
                ('enter_date', models.DateField(verbose_name='入学时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Class', verbose_name='所在班级')),
                ('subjects', models.ManyToManyField(blank=True, to='app.Subjects', verbose_name='选修课程')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='headmaster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Teachers', verbose_name='班主任'),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='选课记录编号')),
                ('choose_year', models.IntegerField(validators=[app.models.test_choose_year], verbose_name='选课年份')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='成绩')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Subjects', validators=[app.models.test_proper_year, app.models.test_complex], verbose_name='课程编号')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students', verbose_name='学生')),
                ('tid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Teachers', verbose_name='教师')),
            ],
            options={
                'verbose_name': '选课信息',
                'verbose_name_plural': '选课信息',
                'unique_together': {('sid', 'cid', 'choose_year')},
            },
        ),
    ]
