# Generated by Django 2.2 on 2019-05-12 14:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190512_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='choose_year',
            field=models.IntegerField(default=2019, validators=[app.models.test_choose_year], verbose_name='选课年份'),
        ),
    ]
